/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 7.0.5 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTEXPR1 = 1;
  public int JJTEXPR2 = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "Expr1",
    "Expr2",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=3c93d6312a299f2c89e8d5fc0fbc1357 (do not edit this line) */
